### ISSUE TITLE
$q for angulargwt

### ISSUE THREAD

**Issue by wiresio** [h0ru5/angulargwt#3]
Hi Johannes,

any idea how to use angular.js' $q (async calls) in angulargwt?

Gruß, Christian.

**Comment by h0ru5** [comment]
unfortunately, GWT-user does not offer wrappers for promises AFAIK
so, either one can wrap $q as service in angularjs, or use exisiting ports, such as GWTquery's implementation.
https://code.google.com/p/gwtquery/wiki/Promises

writing an angulargwt service for $q would of course ease all the $digest-calls

**Comment by h0ru5** [comment]
gwtquery offers A+ promises and is now a transient dep in angulargwt.

a brief example is also in the AngularApp for the script injection
